update component
lyabs-dev/flutter-project-structure pull request #1
Opened 2023-03-29 07:15 UTC by yourimukaz

add component Empty
update page not found

2023-03-29 07:46 UTC, lyabs243 requested changes
Good update, just a little things to change.
Thank you.

2023-03-29 07:46 UTC, lyabs243 commented on assets/images/not_found.png
Beautiful picture with neutral colors but the "404" mean not found and can confuse a user, is it possible to have the same image without the "404"?

2023-03-29 07:46 UTC, lyabs243 commented on lib/presentation/languages/l10n/intl_en.arb
> +    "noResultFound": "No result found !"
Remove the space before "!" so it will become "No result found!"

2023-03-29 07:46 UTC, lyabs243 commented on lib/presentation/empty_widget.dart
This one should be in the folder lib/presentation/components/

2023-04-03 11:18 UTC, yourimukaz commented
modify image found

2023-04-04 08:37 UTC, lyabs243 commented
Don't forget to resolve this "Remove the space before "!" so it will become "No result found!""

2023-04-04 11:51 UTC, yourimukaz commented
add component empty

2023-04-04 18:32 UTC, lyabs243 approved these changes

2023-04-04 18:32 UTC, merged